# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories = Category.create([{ name: 'Liquor store' }, { name: 'Book store' },
                              { name: 'Department store' } , { name: 'Hardware store' },
                              { name: 'Travel agent' }, { name: 'Garden store' },
                              { name: 'Eyewear' }, { name: 'Music store' }, { name: 'Bank' },
                              { name: 'Service Canada' }, { name: 'Pet Shop' }
                             ])
businesses = Business.create ([{ category_id: '1' name: 'Blood Brothers Brewing' address: '165 Geary Ave M6H 2B8' city_id: '1' },
                               { category_id: '1' name: 'Wine Rack' address: '472 Yonge St M4Y 1X5' city_id: '1' },
                               { category_id: '2' name: 'Chapters Indigo' address: '2300 Yonge St M4P 1E0' city_id: '1' },
                               { category_id: '2' name: 'Book City' address: '2354 Bloor St West M6S 1P3' city_id: '1' },
                               { category_id: '3' name: 'Holt Renfrew' address: '50 Bloor St West M4W 1A1' city_id: '1' },
                               { category_id: '3' name: 'Homesense' address: '82 Spadina ave M5V 2J3' city_id: '1' },
                               { category_id: '3' name: 'Marshalls' address: '126 John St M9M 1K1' city_id: '1' },
                               { category_id: '3' name: 'Winners' address: '10 Dundas St East M5b 4G9' city_id: '1' },
                               { category_id: '4' name: 'Homehardware' address: '432 Bloor St West M5S 1X5' city_id: '1' },
                               { category_id: '4' name: 'Canadian Tire' address: '839 Yonge St M4W 2H2' city_id: '1' },
                               { category_id: '5' name: 'Flight Centre' address: '185 Roncesvalles Ave M6R 2L5' city_id: '1' },
                               { category_id: '5' name: 'Elder Treks' address: '597 Markham St M6G 2l7' city_id: '1' },
                               { category_id: '6' name: 'Davenport Garden Centre' address: '368 Davenport Rd M5R 1K6' city_id: '1' },
                               { category_id: '6' name: 'East End Garden Centre' address: '1395 Queen St East M4L 1C7' city_id: '1' },
                               { category_id: '7' name: 'The Optic Zone Inc' address: '33 Jarvis St M5E 1N3' city_id: '1' },
                               { category_id: '7' name: 'Opticianado Eyewear' address: '2919 Dundas St West M6P 1Z1' city_id: '1' },
                               { category_id: '8' name: 'Steves Music Store' address: '415 Queen St West M5V 2A5' city_id: '1' },
                               { category_id: '8' name: 'Long & McQuade' address: '925 Bloor St West M6H 1L5' city_id: '1' },
                               { category_id: '9' name: 'CIBC' address: '1200 King St West M6K 1G4' city_id: '1' },
                               { category_id: '9' name: 'Scotiabank' address: '1616 Dundas St West M6K 1V1' city_id: '1' },
                               { category_id: '9' name: 'TD Canada Trust' address: '61 Hanna Ave M6K 3N7' city_id: '1' },
                               { category_id: '9' name: 'RBC' address: '2 Gladstone Ave M6J 0B2' city_id: '1' },
                               { category_id: '10' name: 'Service Canada' address: '25 St Clair Ave East M4T 3A4' city_id: '1' },
                               { category_id: '10' name: 'Service Canada' address: '559 College St M6G 1A9' city_id: '1' },
                               { category_id: '10' name: 'Service Canada' address: '100 Queen West M5H 2N2' city_id: '1' },
                               { category_id: '11' name: 'Wag on Danforth' address: '1918 Danforth Ave M4C 1J4' city_id: '1' },
                               { category_id: '11' name: 'Dogfather & Co' address: '1007 Yonge St M4W 2K9' city_id: '1' },
                               { category_id: '11' name: 'Annex Pet Supplies' address: '718 Bathurst St M5S 2R4' city_id: '1' }
                               ])
cities = City.create([{ city_name: 'Toronto' business_id: '1' category_id: '1' },
                      { city_name: 'Toronto' business_id: '2' category_id: '1' },
                      { city_name: 'Toronto' business_id: '3' category_id: '2' },
                      { city_name: 'Toronto' business_id: '4' category_id: '2' },
                      { city_name: 'Toronto' business_id: '5' category_id: '3' },
                      { city_name: 'Toronto' business_id: '6' category_id: '3' },
                      { city_name: 'Toronto' business_id: '7' category_id: '3' },
                      { city_name: 'Toronto' business_id: '8' category_id: '3' },
                      { city_name: 'Toronto' business_id: '9' category_id: '4' },
                      { city_name: 'Toronto' business_id: '10' category_id: '4' },
                      { city_name: 'Toronto' business_id: '11' category_id: '5' },
                      { city_name: 'Toronto' business_id: '12' category_id: '5' },
                      { city_name: 'Toronto' business_id: '13' category_id: '6' },
                      { city_name: 'Toronto' business_id: '14' category_id: '6' },
                      { city_name: 'Toronto' business_id: '15' category_id: '7' },
                      { city_name: 'Toronto' business_id: '16' category_id: '7' },
                      { city_name: 'Toronto' business_id: '17' category_id: '8' },
                      { city_name: 'Toronto' business_id: '18' category_id: '8' },
                      { city_name: 'Toronto' business_id: '19' category_id: '9' },
                      { city_name: 'Toronto' business_id: '20' category_id: '9' },
                      { city_name: 'Toronto' business_id: '21' category_id: '9' },
                      { city_name: 'Toronto' business_id: '22' category_id: '9' },
                      { city_name: 'Toronto' business_id: '23' category_id: '10' },
                      { city_name: 'Toronto' business_id: '24' category_id: '10' },
                      { city_name: 'Toronto' business_id: '25' category_id: '10' },
                      { city_name: 'Toronto' business_id: '26' category_id: '11' },
                      { city_name: 'Toronto' business_id: '27' category_id: '11' },
                      { city_name: 'Toronto' business_id: '28' category_id: '11' },
                      }])
